version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rust_backend_stack
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 5s

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/rust_backend_stack
      - HMAC_KEY=random-string
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: wget -O - http://localhost:8080/api/ping || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 5s

volumes:
  dbdata:
    driver: local
