version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rust_backend_stack
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/rust_backend_stack
      - HMAC_KEY=random-string
      - RUST_LOG=debug
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:
    driver: local
